In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

## Analyzing number of paths

In [3]:
## Gathering it all together
def aggregating_means(dir_path):
    means_avoid = pd.read_csv(os.path.join(dir_path, 'means_avoid.csv'), index_col=0)
    means_neutral = pd.read_csv(os.path.join(dir_path, 'means_neutral.csv'),index_col=0)
    means_paved = pd.read_csv(os.path.join(dir_path, 'means_paved.csv'),index_col=0)
    means_prefer = pd.read_csv(os.path.join(dir_path, 'means_prefer.csv'),index_col=0)
    
    means = pd.concat([means_neutral,means_avoid,means_paved, means_prefer])
    means["Setting"] = ["neutral","avoid","prefer","paved"]
    means.set_index("Setting",inplace=True)
    return means




distances = [2000,5000,10000,15000]# ,20000

base_path = "/Users/sofiiashome/Documents/Studying at WU/Bachelor's Thesis/Bachelor Thesis Coding/LoopBuddy/evaluation/results/overall_results_no_sharing_limit"
save_dir = os.path.join(base_path, "distance_aggregated")

for i in distances:
    path = os.path.join(base_path, f"overall_{i}")
    means = aggregating_means(path)
    save_path = os.path.join(save_dir, f"means_{i}.csv")
    means.to_csv(save_path)
    

# aggregating fails:

f2000 = pd.read_csv(os.path.join(os.path.join(base_path, f"overall_{2000}"), 'failed.csv'), index_col=0)
f5000 = pd.read_csv(os.path.join(os.path.join(base_path, f"overall_{5000}"), 'failed.csv'), index_col=0)
f10000 = pd.read_csv(os.path.join(os.path.join(base_path, f"overall_{10000}"), 'failed.csv'), index_col=0)
f15000 = pd.read_csv(os.path.join(os.path.join(base_path, f"overall_{15000}"), 'failed.csv'), index_col=0)


fails_agg = pd.concat([f2000,f5000,f10000,f15000])#,f20000
fails_agg["Distance"] = distances
fails_agg.set_index("Distance",inplace=True)
fails_agg.to_csv(os.path.join(os.path.join(save_dir, f"fails_agg.csv")))

In [4]:

distances = [2000, 5000, 10000, 15000]
base_path = "/Users/sofiiashome/Documents/Studying at WU/Bachelor's Thesis/Bachelor Thesis Coding/LoopBuddy/evaluation/results/overall_results_no_sharing_limit/distance_aggregated"

all_data = []

for dist in distances:
    means_path = os.path.join(base_path, f"means_{dist}.csv")
    df = pd.read_csv(means_path, index_col=0)
    df.reset_index(inplace=True)  # brings 'Setting' back as column
    df.insert(0, "Distance", dist)  # add distance column at front
    df.rename(columns={"Setting": "State"}, inplace=True)  # rename for clarity
    all_data.append(df)

# Combine everything
final_df = pd.concat(all_data)
final_df.to_csv(base_path+"means_combined_distance_state_only.csv", index=False)
display(final_df)

,Distance,State,Elapsed time,N Paths,N stoplights,N steps,N paved edges,N unpaved edges,N unknown edge surfaces,Path badness
0,2000,neutral,3.296588,7.80,3.814085,0.000000,13.350857,0.750781,19.905656,NaN
1,2000,avoid,3.292152,7.82,3.306708,0.000000,13.290558,0.763446,20.201901,12.973141
2,2000,prefer,3.347896,7.88,3.861565,0.000000,13.985653,0.692905,19.618060,35.315792
3,2000,paved,2.944722,7.44,4.538067,0.000000,13.626169,0.812066,20.023467,616.847848
0,5000,neutral,12.426763,8.40,12.817191,0.013636,36.879998,1.147559,43.940914,NaN
1,5000,avoid,11.766489,7.25,10.657434,0.000000,37.190008,1.168104,44.360585,42.453755
2,5000,prefer,11.208659,6.98,12.798243,0.011765,38.762076,0.845783,42.666547,76.119567
3,5000,paved,6.150089,3.89,14.356240,0.025974,35.543926,1.020785,44.904257,1514.017592
0,10000,neutral,57.420734,10.27,28.310491,0.002128,73.581409,2.616089,84.609115,NaN
1,10000,avoid,51.557395,8.85,21.928245,0.003745,72.615272,2.767735,85.907122,96.110077
2,10000,prefer,50.506880,7.82,30.086422,0.003175,78.751803,1.858562,81.153018,146.874513
3,10000,paved,18.533750,1.96,37.336213,0.000000,80.022429,2.562864,83.566490,2958.120598
0,15000,neutral,137.962156,9.95,46.853963,0.022472,113.562946,3.273920,123.226999,NaN
1,15000,avoid,121.485024,6.86,36.783180,0.000000,116.369712,3.675661,125.945465,156.919477
2,15000,prefer,117.272169,6.76,50.474667,0.000000,127.464993,2.925389,120.578630,210.993167
3,15000,paved,34.677935,0.77,58.876126,0.000000,115.695946,2.601351,126.738739,4422.152825

In [5]:
# Measuring difference between two setups:

sharing_lim = pd.read_csv("/Users/sofiiashome/Documents/Studying at WU/Bachelor's Thesis/Bachelor Thesis Coding/LoopBuddy/evaluation/results/overall_results/overall_distance_aggregated/fails_agg.csv")
no_sharing_lim = pd.read_csv("/Users/sofiiashome/Documents/Studying at WU/Bachelor's Thesis/Bachelor Thesis Coding/LoopBuddy/evaluation/results/overall_results_no_sharing_limit/distance_aggregated/fails_agg.csv")

difference = sharing_lim.iloc[:, 1:5] - no_sharing_lim.iloc[:, 1:5]
difference["Distance"] = sharing_lim["Distance"]
display(difference)
difference.to_csv("/Users/sofiiashome/Documents/Studying at WU/Bachelor's Thesis/Bachelor Thesis Coding/LoopBuddy/evaluation/results/diff_in_fails.csv", index=False)

# average = difference.to_numpy().mean()
# print(average)

   Neutral  Avoid  Prefer  Paved  Distance
0     0.04   0.04    0.04   0.04      2000
1     0.05   0.03    0.06   0.05      5000
2     0.05   0.05    0.04   0.07     10000
3     0.04   0.04    0.04   0.02     15000

In [6]:
display(sharing_lim)

   Distance  Neutral  Avoid  Prefer  Paved
0      2000     0.19   0.21    0.23   0.19
1      5000     0.17   0.18    0.29   0.20
2     10000     0.11   0.16    0.43   0.17
3     15000     0.15   0.16    0.67   0.20

In [7]:
display(no_sharing_lim)

   Distance  Neutral  Avoid  Prefer  Paved
0      2000     0.15   0.17    0.19   0.15
1      5000     0.12   0.15    0.23   0.15
2     10000     0.06   0.11    0.39   0.10
3     15000     0.11   0.12    0.63   0.18